[project]
name = "zighang-zighang-embedding"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.2",
    "pypdf>=6.0.0",
    "qdrant-client>=1.15.1",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]
